# Down track distance in meters
down_track: 50.0

# Uptrack distance in meters
up_track: 50.0

# Minimum gap distance to maintain between vehicles in meters
min_gap: 4.0

# Sender id in string
sender_id: 'USDOT-49096'
